plugins:
  - jekyll-seo-tag

locale      : "en_GB"
title       : "Alexander & McMullan - Accountants Ballymoney, Co Antrim"
description : "An amazing website."
url         : "https://alexandermcmullan.co.uk"
repository  : "https://github.com/alexandermcmullan/alexandermcmullan.github.io"
logo        : "/img/logo-two.png"

# Site Author
author:
  name      : "Robert McIlreavy"
  avatar    : "https://secure.gravatar.com/avatar/922d8e543a349e8b943f833375020766"
  location  : "Ballymoney, Northern Ireland"
  twitter   : "mcilreavy"